package moonstone;

/**
 * Created by florian on 1/24/17.
 */

public enum Problem {
    NONE,
    CATCH_EXCEPTION,
    CATCH_THROWABLE,
    THROWS_EXCEPTION,
    THROWS_THROWABLE,
    CATCH_RUNTIMEEXCEPTION,
    CATCH_ERROR,
    EMPTY_CATCH,
    THROWFROMTRY_EXCEPTION,
    THROWFROMTRY_THROWABLE,
    THROWFROMTRY_RUNTIMEEXCEPTION,
    THROWFROMTRY_ERROR,
    DESTRUCTIVE_WRAP,
    RESOURCE_LEAK,
    THROWFROMCATCH_EXCEPTION,
    THROWFROMCATCH_THROWABLE,
    THROWFROMCATCH_RUNTIMEEXCEPTION,
    THROWFROMCATCH_ERROR
}
